[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/godaemon"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-retryablehttp"

[[constraint]]
  name = "github.com/timberio/tail"
  revision = "cc7c82aebf7ca13304456304c4cdaa0c7a7189fc"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.19.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"

[[constraint]]
  name = "github.com/google/go-cmp"
  revision = "3af367b6b30c263d47e8895973edcca9a49cf029"
